# Log
# -*- coding: UTF8 -*-

# NB! This file is auto generated by script makemessages.py. Any changes
# made to it will be overwritten when the script next updates this file.

"""
Outcoming server error and message strings
"""

################################
# Verification protocol errors #
################################

# Error message shown when the query had too many or unknown parameters
BAD_PARAMETERS = \
    'Vigased sisendparameetrid'

# The verification vote ID has expired, reached it's maximum count or is otherwise invalid
INVALID_VOTE_ID = \
    'Seda hääle identifikaatorit ei saa kasutada hääle kontrollimiseks'

# Error message given for internal errors during vore verification
TECHNICAL_ERROR_VOTE_VERIFICATION = \
    'Tehniline viga hääle kontrollimisel'


# vim:set ts=4 sw=4 et fileencoding=utf8:
