#!/bin/sh

set -e

NAME=evote-hes
USER=hes

APA1=/etc/apache2/sites-enabled/hes-apache
APA2=/etc/apache2/sites-available/hes-apache

PORTS_CONF=/etc/apache2/ports.conf.old
if [ -e $PORTS_CONF ] ; then
	mv $PORTS_CONF /etc/apache2/ports.conf
fi

if [ "$1" = remove ] ; then
	if [ -e $APA1 ] ; then rm -f $APA1 ; fi
	if [ -e $APA2 ] ; then rm -f $APA2 ; fi
	invoke-rc.d apache2 stop || true
fi

if [ "$1" = purge ] ; then
	deluser --quiet $USER > /dev/null || true
fi


#DEBHELPER#

